version: '3.4'

services:
  wines-service:
    image: wines-service:production
    container_name: wines-service-production
    depends_on:
      - mongodb
    build:
      context: .
      target: production
    ports:
      - 8080:8080
  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
volumes:
  mongodb-data:
    driver: local

