version: '3.4'

services:
  wines-service:
    image: wines-service:dev
    container_name: wines-service-dev
    depends_on:
      - mongodb
    build:
      context: .
      target: dev
    volumes:
      # do not mount node_modules
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - 8080:8080
    command: npm run dev
  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
volumes:
  mongodb-data:
    driver: local

